Plugin 'nerdtree'
Plugin 'nerdtree'
Plugin 'vim-quickrun'
Plugin 'vim_git'
Plugin 'vim-startify'
Plugin 'YouCompleteMe'
Plugin 'syntastic'
Plugin 'asd'
Plugin '" Plugins list (Press ? for help) "'
Plugin 'asd'
Plugin 'vim-airline'
Plugin 'vim-airline-themes'
Plugin 'vim-airline'
Plugin 'ctrlp.vim'
Plugin 'syntastic'
